stack = [3, 4, 5]
stack.append(8)
stack.append(1)
print(stack)
pop_element = stack.pop()
print(pop_element)
print(stack)
pop_element2= stack.remove(8)
print(pop_element2)
pop_element3 = stack.pop(0)
print(stack)
